import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Kaisei_Tokumin } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-poppins',
});

const kaiseiTokumin = Kaisei_Tokumin({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-kaisei',
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "ChoiceLog",
  description: "Generated by Rachel Barino Silva",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`
          ${kaiseiTokumin.variable}
          ${poppins.variable}
          font-sans
          antialiased
        `}
        >
        {children}
        <Toaster
          richColors
          theme="light"
          position="bottom-right"
          closeButton
        />
      </body>
    </html>
  );
}
